### ISSUE TITLE
Assessment fails with plotting exceptions.

### ISSUE THREAD

**Issue by dcgadmin** [dcgadmin/sctmigrator#1]
When tried to run got below exceptions
_SCT_assessment/assessment.py:22: SyntaxWarning: invalid escape sequence '\A'_

```
SCT_assessment/assessment.py:22: SyntaxWarning: invalid escape sequence '\A'
  parser = argparse.ArgumentParser(description='Capture AWS SCT Extension usage complexity metrics for Proprietary database \n migrated to RDS\Amazon Aurora PostgreSQL Compataible' , formatter_class=RawTextHelpFormatter)
Traceback (most recent call last):
  File "/Users/vpalad/Documents/Automation_tools/Effort_estimation/Sct_extension_pack/sctmigrator/SCT_assessment/assessment.py", line 268, in <module>
    stacked_bar_chart_1(merged_df, output_image_directory)
  File "/Users/vpalad/Documents/Automation_tools/Effort_estimation/Sct_extension_pack/sctmigrator/SCT_assessment/assessment.py", line 112, in stacked_bar_chart_1
    handles = [plt.Rectangle((0,0),1,1, color=custom_color_map[level]) for level in complexity]
```

**Comment by dcgadmin** [comment]
Fix updated in current master branch.

**Comment by dcgadmin** [comment]
Add logic to handle extension function that does not matched.

Default set up

Function category	
'INTERNAL_NOTFOUND'

complexity
'COMPLEX'	

Efforts(Hours)
4
